someengineering/fixbackend

- fixbackend/app.py
> [feat] Add liveness and readiness checks

- .vscode/launch.json
- Makefile
- fixbackend/__main__.py
- fixbackend/app.py
- fixbackend/auth/jwt.py
- fixbackend/auth/oauth.py
- fixbackend/auth/router.py
- fixbackend/auth/user_manager.py
- fixbackend/config.py
- fixbackend/db.py
- fixbackend/organizations/router.py
- pyproject.toml
- tests/fixbackend/auth/router_test.py
- tests/fixbackend/conftest.py
> [feat] Use the dependency mechanism

- Dockerfile
- fixbackend/__main__.py
- fixbackend/config.py
> Do database migrations on startup

- Dockerfile
- fixbackend/__main__.py
- fixbackend/app.py
- fixbackend/config.py
- tests/fixbackend/auth/router_test.py
- tests/fixbackend/config_test.py
- tests/fixbackend/conftest.py
> [feat] Split parameters and add dumb-init

- fixbackend/app.py
> Make sure static folder route is the latest

- fixbackend/__main__.py
> Support proxy headers from everywhere

- Dockerfile
> Add the templates folder to the docker container

- .github/workflows/docker_build.yml
> Bump fixbackend when merging to main

- .devcontainer/Dockerfile
- .devcontainer/docker-compose.yml
- .devcontainer/postCreate.sh
- alembic.ini
- fixbackend/auth/dependencies.py
- fixbackend/auth/jwt.py
- fixbackend/auth/redirect_to_spa.py
- fixbackend/auth/router.py
- fixbackend/auth/user_manager.py
- fixbackend/auth/user_verifier.py
- tests/fixbackend/auth/router_test.py
> Use cookies instead of bearer token for transport

- fixbackend/app.py
- fixbackend/auth/router.py
- fixbackend/auth/user_manager.py
- fixbackend/config.py
- tests/fixbackend/auth/router_test.py
> Create a default organization and remove the /login url

- fixbackend/auth/dependencies.py
- fixbackend/auth/jwt.py
- fixbackend/auth/oauth.py
- fixbackend/auth/redirect_to_spa.py
- fixbackend/auth/router.py
- fixbackend/config.py
- tests/fixbackend/conftest.py
- tests/fixbackend/organizations/router_test.py
> Use secure cookie and make redirect url configurable

- fixbackend/config.py
> Update the name of the oauth url env var

- fixbackend/auth/oauth.py
- fixbackend/auth/router.py
- fixbackend/config.py
- tests/fixbackend/conftest.py
> Allow dynamic redirect after oauth call

- fixbackend/organizations/router.py
- fixbackend/organizations/schemas.py
- tests/fixbackend/organizations/router_test.py
> Add an external_id endpoint

- fixbackend/app.py
- fixbackend/cloud_accounts/router.py
- fixbackend/cloud_accounts/schemas.py
- pyproject.toml
- tests/fixbackend/cloud_accounts/router_test.py
> Add a cloudformation template callback api

- fixbackend/app.py
- poetry.lock
- pyproject.toml
> [feat] Add /metrics endpoint

- fixbackend/auth/cookies.py
- fixbackend/auth/jwt.py
- fixbackend/auth/transport.py
> Allow cookie auth on the websocket endpoint

- fixbackend/app.py
> Return 404 only on API routes

- .devcontainer/devcontainer.json
- .vscode/launch.json
- .vscode/settings.json
- fixbackend/all_models.py
- fixbackend/auth/db.py
- fixbackend/auth/dependencies.py
- fixbackend/auth/models/__init__.py
- fixbackend/auth/models/orm.py
- fixbackend/auth/user_manager.py
- fixbackend/auth/user_verifier.py
- fixbackend/organizations/models.py
- fixbackend/organizations/service.py
- tests/fixbackend/auth/router_test.py
- tests/fixbackend/organizations/router_test.py
- tests/fixbackend/organizations/service_test.py
> Use an immutable user model

- fixbackend/app.py
> Disable logging on k8s internal endpoints

- fixbackend/app.py
- fixbackend/auth/router.py
- fixbackend/config.py
> Add a user management endpoint

- fixbackend/cloud_accounts/repository.py
- pyproject.toml
- tests/fixbackend/app_test.py
> Fix openapi docs generation

- fixbackend/app.py
- fixbackend/cloud_accounts/service.py
- fixbackend/dependencies.py
- tests/fixbackend/cloud_accounts/service_test.py
> Publish a message about account creation/deletion

- fixbackend/organizations/repository.py
- fixbackend/organizations/router.py
- tests/fixbackend/organizations/repository_test.py
- tests/fixbackend/organizations/router_test.py
> Fix the organisation repository: allow multiple orgs

- fixbackend/collect/collect_queue.py
- tests/fixbackend/collect/collect_queue_test.py
> [fix] Make job definition json compliant

- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/dispatcher/next_run_repository.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
- tests/fixbackend/dispatcher/next_run_repository_test.py
> [feat] Compute next_run based on last_run

- fixbackend/app.py
- poetry.lock
> [feat] Setup fix logging

- fixbackend/keyvalue/__init__.py
- fixbackend/keyvalue/json_kv.py
- migrations/versions/2023-10-02T12:17:40Z_add_json_kv_store.py
- tests/fixbackend/keyvalue/json_kv_test.py
> Add a json key value store

- migrations/versions/2023-10-02T12:17:40Z_add_json_kv_store.py
> [fix] make database history linear

- .github/workflows/build_and_test.yml
> Cache the devcontainer image when runing tests

- noxfile.py
- poetry.lock
- pyproject.toml
> [chore] Add type sheds as dev dependency

- .github/workflows/build_and_test.yml
- fixbackend/sqs.py
- noxfile.py
- poetry.lock
- pyproject.toml
> [feat] Implement a SQS publisher and listener

- fixbackend/config.py
> Update the default aws region

- fixbackend/organizations/router.py
- tests/fixbackend/organizations/router_test.py
> add the url with CF templates

- fixbackend/__main__.py
- fixbackend/app.py
- fixbackend/certificates/cert_store.py
- fixbackend/config.py
- fixbackend/dependencies.py
- fixbackend/inventory/inventory_client.py
- tests/fixbackend/conftest.py
> Allow https

- fixbackend/app.py
> [fix] aiomysql parameter

- fixbackend/app.py
> Disable tls on mysql connections for now

- websocket_events.md
> [feat] Describe websocket event structure

- fixbackend/metering/metering_repository.py
> [fix] Define columns as nullable

- websocket_events.md
> Update websocket docs

- fixbackend/app.py
- static/openapi-events.yaml
> Add the domain events specification

- fixbackend/app.py
- fixbackend/auth/user_manager.py
- fixbackend/cloud_accounts/service.py
- fixbackend/config.py
- fixbackend/dependencies.py
- fixbackend/domain_events/__init__.py
- fixbackend/domain_events/dependencies.py
- fixbackend/domain_events/events.py
- fixbackend/domain_events/sender.py
- fixbackend/domain_events/sender_impl.py
- pyproject.toml
- static/openapi-events.yaml
- tests/fixbackend/auth/jwt_strategy_test.py
- tests/fixbackend/auth/router_test.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/domain_events/__init__.py
- tests/fixbackend/domain_events/sender_impl_test.py
> Publish domain events on cloud account discovery and user registration

- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> [fix] Name of account id in message

- Dockerfile
> copy the static folder

- fixbackend/app.py
- fixbackend/config.py
- fixbackend/dependencies.py
- fixbackend/domain_events/consumers.py
- fixbackend/domain_events/converter.py
- fixbackend/domain_events/events.py
- fixbackend/domain_events/sender_impl.py
- tests/fixbackend/conftest.py
- tests/fixbackend/domain_events/sender_impl_test.py
> Send user registration events to customer.io

- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/schemas.py
- tests/fixbackend/inventory/inventory_service_test.py
Also deal with empty account ids.
> [feat] Improve VulnerabilitiesChanged

- fixbackend/app.py
- fixbackend/config.py
> [feat]: Allow redis passwords

- fixbackend/inventory/inventory_service.py
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat]: Improve the scoring mechanism

- fixbackend/app.py
- fixbackend/config.py
- tests/fixbackend/conftest.py
> Define cors config

- fixbackend/app.py
> Enable connection pool recycling

- fixbackend/subscription/router.py
> [fix] resolve the route (again)

- fixbackend/auth/auth_backend.py
- fixbackend/auth/transport.py
> Relax samesite cookie policy

- fixbackend/subscription/router.py
> [fix] handle cross-origin post

- fixbackend/subscription/router.py
> [fix] wrong redirect code

- fixbackend/subscription/aws_marketplace.py
- fixbackend/subscription/subscription_repository.py
- tests/fixbackend/subscription/subscription_repository_test.py
> [feat] Handle subscription messages

- fixbackend/sqs.py
> [fix] SQS float->int and error logging

- fixbackend/app.py
- fixbackend/config.py
- fixbackend/sqs.py
- fixbackend/subscription/aws_marketplace.py
> [fix] Handle raw sqs message

- fixbackend/auth/user_verifier.py
> [fix] Email verification link

- .github/workflows/docker_build.yml
- fixbackend/__main__.py
- fixbackend/app.py
- fixbackend/middleware/x_real_ip.py
> Log real ip address

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- poetry.lock
- pyproject.toml
> [chore] Bump libs

- fixbackend/subscription/aws_marketplace.py
- tests/fixbackend/subscription/aws_marketplace_test.py
> [fix] AWS metering report

- Makefile
- fixbackend/subscription/aws_marketplace.py
- fixbackend/subscription/billing.py
- fixbackend/subscription/subscription_repository.py
- tests/fixbackend/subscription/billing_test.py
> [feat] Report no usage for all active subscriptions

- fixbackend/workspaces/dependencies.py
> Gracefully handle unauthorized in websocket

- .vscode/launch.json
- fixbackend/auth/auth_backend.py
- fixbackend/auth/depedencies.py
- tests/fixbackend/auth/router_test.py
> Fix swagger docs

- fixbackend/app.py
- fixbackend/auth/auth_backend.py
> Always set logout cookies on 401

- fixbackend/app.py
- fixbackend/config.py
- tests/fixbackend/conftest.py
- tests/fixbackend/events/router_test.py
- tests/fixbackend/organizations/router_test.py
> Remove cors middleware and /organizations routes

- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/router.py
- fixbackend/inventory/schemas.py
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Add search start data

- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/router.py
- fixbackend/streaming_response.py
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Add /search/list endpoint

- fixbackend/inventory/router.py
> [fix] Revert removal of workspace id

- fixbackend/inventory/inventory_service.py
> [fix] Search start data

- fixbackend/cloud_accounts/schemas.py
- fixbackend/cloud_accounts/service.py
- fixbackend/cloud_accounts/service_impl.py
- tests/fixbackend/cloud_accounts/router_test.py
- tests/fixbackend/cloud_accounts/service_test.py
> Allow removing an account name

- .devcontainer/devcontainer.json
- fixbackend/app.py
- fixbackend/auth/auth_backend.py
- fixbackend/auth/depedencies.py
- fixbackend/certificates/cert_store.py
- fixbackend/cloud_accounts/router.py
- fixbackend/cloud_accounts/service_impl.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/logging_context.py
- fixbackend/workspaces/dependencies.py
- poetry.lock
- pyproject.toml
> Provide context to the logger

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/router.py
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_client_test.py
> [feat] Allow listing of possible attributes and values

- .github/workflows/docker_build.yml
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/logging_context.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> [fix] Also handle failing collect results 

- fixbackend/ids.py
- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/router.py
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_client_test.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Add inventory resource endpoint

- fixbackend/cloud_accounts/account_setup.py
- fixbackend/cloud_accounts/models/__init__.py
- fixbackend/cloud_accounts/models/orm.py
- fixbackend/cloud_accounts/schemas.py
- fixbackend/cloud_accounts/service.py
- fixbackend/cloud_accounts/service_impl.py
- fixbackend/collect/collect_queue.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/ids.py
- tests/fixbackend/cloud_accounts/repository_test.py
- tests/fixbackend/cloud_accounts/router_test.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/collect/collect_queue_test.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> Use more typed ids and fix the wrong external id bug

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Lookup kind names

- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> Cleanup the dispatcher service

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/dispatcher/dispatcher_service.py
> Fix logging in dispatching

- fixbackend/cloud_accounts/account_setup.py
- fixbackend/cloud_accounts/models/__init__.py
- fixbackend/dispatcher/collect_progress.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/domain_events/events.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> Handle collect job errors in dispatcher

- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> Do not schedule collections if the tenant is not collected yet

- fixbackend/app.py
- fixbackend/dependencies.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/domain_events/consumers.py
- fixbackend/domain_events/subscriber.py
- fixbackend/inventory/inventory_service.py
- tests/fixbackend/conftest.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
- tests/fixbackend/domain_events/subscriber_test.py
- tests/fixbackend/inventory/inventory_service_test.py
> Delete accounts in arrangodb on receiving an event

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/router.py
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_client_test.py
> [feat] Complete property names

- fixbackend/inventory/inventory_service.py
> [fix] Sort accounts by score

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/router.py
> [fix] do not send null values

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/router.py
- fixbackend/inventory/schemas.py
- tests/fixbackend/inventory/inventory_client_test.py
> [fix] Use json instead of form parameters

- fixbackend/cloud_accounts/repository.py
- fixbackend/cloud_accounts/service_impl.py
- tests/fixbackend/cloud_accounts/repository_test.py
> Correct the cloud account update

- fixbackend/inventory/inventory_client.py
- tests/fixbackend/cloud_accounts/repository_test.py
- tests/fixbackend/inventory/inventory_client_test.py
> [fix] Fix json marshalling

- fixbackend/cloud_accounts/schemas.py
- tests/fixbackend/cloud_accounts/router_test.py
> Expose priviledged account flag

- fixbackend/app.py
> [feat] Make the component name more specific

- fixbackend/inventory/inventory_client.py
> [fix] Filter by empty list is ignored

- fixbackend/cloud_accounts/schemas.py
- tests/fixbackend/cloud_accounts/router_test.py
> Add the last_collected in the cloud_account json

- poetry.lock
> [chore] Bump libraries

- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/router.py
- fixbackend/inventory/schemas.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Support history search

- fixbackend/cloud_accounts/service_impl.py
> Start the configure cloud accounts job

- fixbackend/cloud_accounts/service_impl.py
> Start cloud account job only if defined

- fixbackend/inventory/inventory_service.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] sort search start data

- fixbackend/inventory/router.py
- fixbackend/inventory/schemas.py
> [feat] table endpoint uses json

- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/schemas.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] ReportSummary: summary over all accounts

- fixbackend/app.py
- fixbackend/sqlalechemy_extensions.py
- fixbackend/sqs.py
> [feat] Add metrics for sqs and database

- fixbackend/app.py
- fixbackend/errors.py
- fixbackend/inventory/inventory_client.py
> [fix] Inventory errors should respond with 4xx not 5xx

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/sqs.py
> [fix] Increment failing counter in the handler

- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/schemas.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Report Summary: add resource counts to summaries

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Resource detail: add the failing checks as part of the resource

- fixbackend/cloud_accounts/service_impl.py
- tests/fixbackend/cloud_accounts/service_test.py
> [fix] fix multi region cf handler

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/domain_events/events.py
- tests/fixbackend/domain_events/test_events.py
> [fix] Json event marshalling

- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/schemas.py
- tests/fixbackend/inventory/inventory_service_test.py
> feat: return the unique failing count

- fixbackend/inventory/inventory_service.py
> fix: sort resource checks

- fixbackend/app.py
- fixbackend/config.py
- tests/fixbackend/conftest.py
> feat: make env available to the frontend

- fixbackend/cloud_accounts/models/__init__.py
- fixbackend/cloud_accounts/models/orm.py
- fixbackend/cloud_accounts/repository.py
- fixbackend/cloud_accounts/service_impl.py
- tests/fixbackend/cloud_accounts/repository_test.py
- tests/fixbackend/cloud_accounts/service_test.py
> Add cloud account deleted state

- fixbackend/inventory/inventory_service.py
> [fix] Multiple situations indicate that the inventory is not ready

- fixbackend/__main__.py
- migrations/versions/2023-12-07T12:14:35Z_update_workspace_invites.py
> Check the correct database revision on start

- fixbackend/cloud_accounts/router.py
- fixbackend/cloud_accounts/schemas.py
- fixbackend/cloud_accounts/service_impl.py
- pyproject.toml
- tests/fixbackend/cloud_accounts/router_test.py
- tests/fixbackend/cloud_accounts/service_test.py
> Add account categories to cloud account list endpoint

- fixbackend/app.py
- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- poetry.lock
- pyproject.toml
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Add caching for inventory service data

- fixbackend/app.py
> [fix] Use redis temp store

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/schemas.py
- tests/fixbackend/inventory/inventory_client_test.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Add time series for vulnerable resources

- fixbackend/events/router.py
> [feat] Use a proper websocket close code

- fixbackend/cloud_accounts/models/__init__.py
- fixbackend/cloud_accounts/service_impl.py
- fixbackend/collect/collect_queue.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/domain_events/events.py
- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_client_test.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Change account name in inventory, when changed in fix

- fixbackend/__main__.py
- fixbackend/alembic_startup_utils.py
- fixbackend/alembic_stratup_utils.py
- fixbackend/metering/metering_repository.py
- tests/fixbackend/conftest.py
> Update the migration version check mechanism

- fixbackend/collect/collect_queue.py
- fixbackend/dispatcher/dispatcher_service.py
> [feat] Defer and retry first collect

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/inventory/inventory_service.py
- tests/fixbackend/cloud_accounts/service_test.py
> [fix] Trigger change name event on organizational listing

- fixbackend/app.py
- fixbackend/subscription/aws_marketplace.py
- fixbackend/subscription/router.py
- fixbackend/subscription/subscription_repository.py
- fixbackend/workspaces/router.py
- tests/fixbackend/subscription/subscription_repository_test.py
- tests/fixbackend/subscription/subscription_router_test.py
- tests/fixbackend/workspaces/router_test.py
> Ask to select select which workspace to use for subscription

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/inventory/inventory_service.py
> [fix] Configure discovered accounts should give up

- fixbackend/workspaces/schemas.py
> Pre-fill user sources for fix

- fixbackend/workspaces/schemas.py
> Update WorkspaceInviteRead schema with invite_id field

- fixbackend/app.py
- fixbackend/config.py
- poetry.lock
- pyproject.toml
- tests/fixbackend/conftest.py
> Add request profiling on demand

- fixbackend/app.py
> [feat] Add /api/info endpoint

- fixbackend/app.py
- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/router.py
- fixbackend/inventory/schemas.py
- fixbackend/subscription/router.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Allow custom checks, benchmarks and report config

- fixbackend/app.py
- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
> [feat] Improve prometheus latency metrics

- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/router.py
- fixbackend/inventory/schemas.py
- fixbackend/streaming_response.py
- pyproject.toml
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_service_test.py
- tests/fixbackend/streaming_response_test.py
> [feat] Inventory CSV download

- fixbackend/inventory/inventory_client.py
> [fix] Workaround for graph database not available

- fixbackend/app.py
- fixbackend/dependencies.py
- fixbackend/domain_events/consumers.py
> Send an email on signup

- fixbackend/notification/messages.py
- fixbackend/notification/templates/signup.html
> Use the designer template for sign-up emails

- fixbackend/inventory/router.py
> [fix] add search content headers

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Create graph database when workspace is created

- fixbackend/auth/user_repository.py
> add the missing await

- fixbackend/dispatcher/collect_progress.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/domain_events/events.py
- fixbackend/ids.py
- fixbackend/notification/service.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
- tests/fixbackend/domain_events/test_events.py
> Include TaskIds in the TenantWorkspaceCollected event

- fixbackend/config.py
- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Create an empty graph on database creation

- fixbackend/subscription/aws_marketplace.py
- tests/fixbackend/subscription/aws_marketplace_test.py
> Report 0 usage on free tier accounts

- fixbackend/workspaces/dependencies.py
> Handle the error codes properly in get_user_workspace dependency

- fixbackend/app.py
- fixbackend/config.py
- fixbackend/domain_events/events.py
- fixbackend/subscription/aws_marketplace.py
- fixbackend/utils.py
- tests/fixbackend/conftest.py
- tests/fixbackend/subscription/aws_marketplace_test.py
> Make billing period adjustable and add a subscription event

- fixbackend/app.py
- fixbackend/auth/oauth_router.py
- fixbackend/auth/router.py
- fixbackend/auth/schemas.py
> Add OAuth provider associate endpoint

- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/schemas.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Allow to define sort order as part of the search query

- poetry.lock
- pyproject.toml
> Update dependencies in pyproject.toml

- fixbackend/auth/router.py
- fixbackend/auth/schemas.py
- fixbackend/auth/user_manager.py
- fixbackend/auth/user_repository.py
> Add OAuth account unlinking functionality

- fixbackend/auth/auth_backend.py
- tests/fixbackend/auth/jwt_strategy_test.py
> Do not explode whin decoding an invalid token

- fixbackend/auth/user_manager.py
- fixbackend/auth/user_verifier.py
- fixbackend/notification/email/email_messages.py
- fixbackend/notification/email/templates/password_reset.html
- tests/fixbackend/auth/jwt_strategy_test.py
- tests/fixbackend/auth/router_test.py
> Send password reset email

- fixbackend/notification/notification_provider_config_repo.py
- fixbackend/notification/notification_router.py
- fixbackend/notification/notification_service.py
> [feat] Return readable notification config

- fixbackend/analytics/__init__.py
- fixbackend/analytics/analytics_event_sender.py
- fixbackend/analytics/domain_event_to_analytics.py
- fixbackend/analytics/events.py
- fixbackend/app.py
- fixbackend/auth/user_manager.py
- fixbackend/billing_information/service.py
- fixbackend/cloud_accounts/service_impl.py
- fixbackend/dependencies.py
- fixbackend/domain_events/events.py
- fixbackend/ids.py
- fixbackend/inventory/inventory_service.py
- fixbackend/notification/model.py
- fixbackend/notification/notification_provider_config_repo.py
- fixbackend/notification/notification_router.py
- fixbackend/notification/notification_service.py
- fixbackend/subscription/aws_marketplace.py
- fixbackend/workspaces/repository.py
- tests/fixbackend/analytics/analytics_event_sender_test.py
- tests/fixbackend/auth/router_test.py
- tests/fixbackend/billing_information/billing_info_service_test.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/conftest.py
> [feat] Improve domain and analytics events

- fixbackend/inventory/inventory_service.py
> [fix] use the correct severity path

- fixbackend/cloud_accounts/service_impl.py
> [fix] Variable usage

- fixbackend/analytics/analytics_event_sender.py
- poetry.lock
- pyproject.toml
> [fix] lrucache -> alrucache

- fixbackend/certificates/cert_store.py
> [fix] Do not use deprecated API cryptography

- fixbackend/app.py
- fixbackend/httpx_extensions.py
- fixbackend/notification/discord/discord_notification.py
- fixbackend/notification/notification_service.py
- fixbackend/notification/pagerduty/pagerduty_notification.py
- fixbackend/notification/slack/slack_notification.py
- fixbackend/notification/teams/teams_notification.py
- tests/fixbackend/notification/discord_notification_test.py
- tests/fixbackend/notification/pagerduty_notification_test.py
- tests/fixbackend/notification/slack_notification_test.py
- tests/fixbackend/notification/teams_notification_test.py
> [feat] Improve http response handling

- fixbackend/__main__.py
- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
> [fix] do not warn of expected behavior

- fixbackend/inventory/router.py
> [feat] Add node history endpoint

- fixbackend/workspaces/repository.py
> [fix] Wrong log statement

- fixbackend/app.py
- fixbackend/cloud_accounts/service_impl.py
- fixbackend/errors.py
- fixbackend/workspaces/invitation_repository.py
- fixbackend/workspaces/invitation_service.py
- fixbackend/workspaces/repository.py
- tests/fixbackend/workspaces/invitation_service_test.py
> Fix workspace membership removal when user is not a member

- fixbackend/auth/oauth_router.py
> Fix OAuth callback redirect URL and handle error cases

- fixbackend/analytics/domain_event_to_analytics.py
- fixbackend/analytics/events.py
- fixbackend/billing_information/router.py
- fixbackend/billing_information/schemas.py
- fixbackend/billing_information/service.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/domain_events/events.py
- fixbackend/ids.py
- fixbackend/metering/__init__.py
- fixbackend/metering/metering_repository.py
- fixbackend/subscription/aws_marketplace.py
- fixbackend/subscription/billing.py
- fixbackend/subscription/models.py
- fixbackend/subscription/subscription_repository.py
- fixbackend/workspaces/models/__init__.py
- fixbackend/workspaces/models/orm.py
- fixbackend/workspaces/repository.py
- tests/fixbackend/billing_information/billing_info_router_test.py
- tests/fixbackend/billing_information/billing_info_service_test.py
- tests/fixbackend/cloud_accounts/router_test.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/events/router_test.py
- tests/fixbackend/metering/metering_repository_test.py
- tests/fixbackend/subscription/aws_marketplace_test.py
- tests/fixbackend/subscription/billing_test.py
- tests/fixbackend/subscription/subscription_repository_test.py
- tests/fixbackend/workspaces/repository_test.py
- tests/fixbackend/workspaces/router_test.py
> [feat] Use new pricing tears

- fixbackend/auth/models/__init__.py
- fixbackend/cloud_accounts/router.py
- fixbackend/notification/notification_router.py
- fixbackend/workspaces/router.py
- tests/fixbackend/cloud_accounts/router_test.py
> Add workspace permission flags for reading and updating settings and cloud accounts

- fixbackend/auth/oauth_router.py
> Fail fast on invalid oauth state token

- fixbackend/billing_information/schemas.py
- tests/fixbackend/billing_information/billing_info_router_test.py
> Update product tier to lowercase in schemas.py

- fixbackend/billing_information/router.py
- fixbackend/billing_information/schemas.py
- tests/fixbackend/billing_information/billing_info_router_test.py
> Update billing information schema and router

- fixbackend/notification/notification_service.py
> [fix] Delete messaging config

- fixbackend/notification/email/templates/signup.html
> Fix email link in signup template

- fixbackend/app.py
> [feat] Add GZIP compression

- fixbackend/ids.py
- fixbackend/notification/notification_router.py
- fixbackend/notification/notification_service.py
- fixbackend/notification/opsgenie/__init__.py
- fixbackend/notification/opsgenie/opsgenie_notification.py
- tests/fixbackend/notification/opsgenie_notification_test.py
> [feat] Add opsgenie event notification sender

- fixbackend/billing_information/schemas.py
- fixbackend/ids.py
- fixbackend/metering/metering_repository.py
- fixbackend/subscription/subscription_repository.py
- fixbackend/workspaces/models/orm.py
> Make ProductTier backwards compatible

- fixbackend/subscription/aws_marketplace.py
> Report no usage in billing if there are no summaries

- fixbackend/billing_information/service.py
- fixbackend/metering/metering_repository.py
- fixbackend/workspaces/models/orm.py
- fixbackend/workspaces/repository.py
- migrations/versions/2024-02-22T12:00:00Z_migrate_product_tier.py
- tests/fixbackend/billing_information/billing_info_router_test.py
- tests/fixbackend/billing_information/billing_info_service_test.py
- tests/fixbackend/workspaces/repository_test.py
- tests/fixbackend/workspaces/router_test.py
> [chore] migrate existing security tiers into product tiers

- fixbackend/subscription/aws_marketplace.py
- tests/fixbackend/conftest.py
- tests/fixbackend/subscription/aws_marketplace_test.py
- tests/fixbackend/subscription/billing_test.py
> [fix] translate product tier to aws marketplace dimension

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/sqs.py
- fixbackend/subscription/aws_marketplace.py
> [fix] adjust sqs defaults

- fixbackend/ids.py
- fixbackend/notification/model.py
- fixbackend/notification/notification_router.py
- fixbackend/notification/notification_service.py
- tests/fixbackend/notification/notification_provider_config_repo_test.py
- tests/fixbackend/notification/notification_service_test.py
- tests/fixbackend/notification/workspace_alert_config_repo_test.py
> Handle the opsgenie notification parsing

- fixbackend/billing_information/router.py
- fixbackend/billing_information/schemas.py
- fixbackend/billing_information/service.py
> Product tier logic update fix

- migrations/versions/2024-02-21T17:26:49Z_scan_flag.py
> [fix] Use correct column

- fixbackend/app.py
- fixbackend/billing_information/router.py
> Add an AWS marketplace redirect link

- fixbackend/subscription/subscription_repository.py
> Refactor query in SubscriptionRepository to use multiple where clauses

- fixbackend/billing_information/router.py
- fixbackend/billing_information/schemas.py
- tests/fixbackend/billing_information/billing_info_router_test.py
- tests/fixbackend/workspaces/repository_test.py
> Billing page JSON handling

- fixbackend/billing_information/schemas.py
- tests/fixbackend/billing_information/billing_info_router_test.py
> Product tier: free -> Free

- fixbackend/app.py
- fixbackend/auth/auth_backend.py
- fixbackend/certificates/cert_store.py
- fixbackend/config.py
- fixbackend/dependencies.py
- fixbackend/jwt/__init__.py
- fixbackend/notification/discord/discord_notification.py
- fixbackend/notification/email/email_messages.py
- fixbackend/notification/email/email_notification.py
- fixbackend/notification/email/email_sender.py
- fixbackend/notification/email/templates/base.html
- fixbackend/notification/email/templates/failing_benchmarks_detected.html
- fixbackend/notification/email/templates/signup.html
- fixbackend/notification/notification_router.py
- fixbackend/notification/notification_service.py
- tests/fixbackend/auth/router_test.py
- tests/fixbackend/conftest.py
- tests/fixbackend/notification/email_notification_test.py
- tests/fixbackend/notification/notification_service_test.py
> SES emails improvement

- fixbackend/inventory/router.py
> [fix] Sort order

- fixbackend/config.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/ids.py
- fixbackend/workspaces/invitation_service.py
- fixbackend/workspaces/repository.py
- fixbackend/workspaces/router.py
- tests/fixbackend/conftest.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
- tests/fixbackend/workspaces/invitation_service_test.py
- tests/fixbackend/workspaces/repository_test.py
> Add limits on seats and scan frequency depending on product tier

- fixbackend/config.py
- fixbackend/notification/discord/discord_notification.py
- fixbackend/notification/email/templates/base.html
- fixbackend/notification/email/templates/signup.html
- fixbackend/notification/pagerduty/pagerduty_notification.py
- fixbackend/notification/slack/slack_notification.py
- fixbackend/notification/teams/teams_notification.py
> [fix] cdn.some.engineering --> cdn.fix.security

- fixbackend/app.py
> Use more security headers

- fixbackend/app.py
> Add unsafe-inline and form-action self to CSP

- fixbackend/app.py
> Use nonce for style elements

- fixbackend/app.py
> Add nonce for scripts

- fixbackend/auth/models/orm.py
- fixbackend/auth/user_manager.py
- fixbackend/auth/user_repository.py
- fixbackend/dependencies.py
- fixbackend/permissions/models.py
- fixbackend/workspaces/router.py
- fixbackend/workspaces/schemas.py
- tests/fixbackend/auth/jwt_strategy_test.py
- tests/fixbackend/auth/router_test.py
- tests/fixbackend/conftest.py
- tests/fixbackend/workspaces/router_test.py
> Show user roles in workspace/users endpoint

- fixbackend/inventory/router.py
> [fix] id should be quoted

- fixbackend/app.py
> Add HSTS header with recommended values

- fixbackend/dispatcher/dispatcher_service.py
> Add redis expiration transactionally with data

- fixbackend/notification/email/email_messages.py
- fixbackend/notification/email/email_sender.py
- fixbackend/notification/email/templates/account_degraded.html
- tests/fixbackend/notification/notification_service_test.py
> [fix] left overs from URL change

- fixbackend/inventory/inventory_service.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Top Checks include the related benchmark

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/router.py
- fixbackend/inventory/schemas.py
> [feat] Provide a search endpoint

- fixbackend/workspaces/models/__init__.py
- fixbackend/workspaces/schemas.py
> Add trial_end field to WorkspaceRead schema

- fixbackend/inventory/inventory_client.py
> [fix] Make sure content is read

- fixbackend/inventory/router.py
- fixbackend/streaming_response.py
> [fix] Streaming response handler

- fixbackend/workspaces/models/__init__.py
- fixbackend/workspaces/schemas.py
> [feat] Use trail_end_days instead of trial_end

- fixbackend/inventory/inventory_service.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] also fetch ignored checks

- fixbackend/inventory/inventory_service.py
> [fix] list extend not append

- fixbackend/all_models.py
- fixbackend/app.py
- fixbackend/auth/models/orm.py
- fixbackend/dependencies.py
- fixbackend/notification/email/email_messages.py
- fixbackend/notification/email/scheduled_email.py
- fixbackend/notification/email/templates/day1.html
- fixbackend/notification/email/templates/day1.subject
- fixbackend/notification/email/templates/day1.txt
- fixbackend/notification/email/templates/day2.html
- fixbackend/notification/email/templates/day2.subject
- fixbackend/notification/email/templates/day2.txt
- fixbackend/notification/email/templates/day3.html
- fixbackend/notification/email/templates/day3.subject
- fixbackend/notification/email/templates/day3.txt
- fixbackend/notification/email/templates/day4.html
- fixbackend/notification/email/templates/day4.subject
- fixbackend/notification/email/templates/day4.txt
- fixbackend/notification/email/templates/day5.html
- fixbackend/notification/email/templates/day5.subject
- fixbackend/notification/email/templates/day5.txt
- migrations/versions/2024-03-27T08:42:43Z_scheduled_email.py
- tests/fixbackend/auth/router_test.py
- tests/fixbackend/notification/scheduled_email_test.py
- tools/render_template.py
> [feat] Send Fix 101 newsletter emails

- fixbackend/graph_db/models.py
- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/router.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Allow listing of benchmarks and checks

- fixbackend/app.py
- fixbackend/auth/schemas.py
- fixbackend/auth/users_router.py
- fixbackend/dependencies.py
- fixbackend/ids.py
- fixbackend/notification/email/email_sender.py
- fixbackend/notification/email/scheduled_email.py
- fixbackend/notification/notification_router.py
- fixbackend/notification/user_notification_repo.py
- migrations/versions/2024-04-02T08:42:50Z_tutorial_emails.py
- tests/fixbackend/auth/users_router_test.py
- tests/fixbackend/conftest.py
- tests/fixbackend/notification/scheduled_email_test.py
- tests/fixbackend/notification/user_notification_repo_test.py
> [feat] Allow unsubscribing from tutorial

- fixbackend/billing_information/service.py
- fixbackend/workspaces/repository.py
- tests/fixbackend/billing_information/billing_info_service_test.py
- tests/fixbackend/workspaces/repository_test.py
> Use trial tier by default when creating a workspace

- fixbackend/inventory/inventory_service.py
- fixbackend/sqlalechemy_extensions.py
> [fix] Signature and log level

- fixbackend/app.py
> [fix] Redis client handling

- fixbackend/notification/email/email_sender.py
- fixbackend/notification/user_notification_repo.py
- tests/fixbackend/notification/user_notification_repo_test.py
> [fix] unsubscribe URL

- fixbackend/app.py
> Use readwrite redis for healthcheck

- fixbackend/analytics/events.py
- fixbackend/analytics/router.py
- fixbackend/app.py
- fixbackend/notification/email/email_messages.py
- fixbackend/notification/email/scheduled_email.py
- fixbackend/notification/email/templates/base.html
- tests/fixbackend/analytics/analytics_router_test.py
- tests/fixbackend/conftest.py
- tools/render_template.py
> [feat] Email open analytics

- fixbackend/app.py
> Print app CDN url on start

- fixbackend/inventory/router.py
> [fix] Show all query parameters

- fixbackend/analytics/router.py
- fixbackend/notification/email/email_messages.py
- fixbackend/notification/email/templates/base.html
> feat: ensure unique email link

- fixbackend/__main__.py
- fixbackend/dependencies.py
```sh
Interrupt received, shutting down...
2024-04-04T09:56:40 INFO Shutting down
2024-04-04T09:56:40 INFO Waiting for application shutdown.
2024-04-04T09:56:40 INFO Application shutdown complete.
▶ echo $?           
0
```
> [feat] Shutdown gracefully

- fixbackend/notification/email/scheduled_email.py
- fixbackend/notification/email/templates/no_cloud_account.html
- fixbackend/notification/email/templates/no_cloud_account.txt
- tests/fixbackend/notification/scheduled_email_test.py
> [feat] Email users that do not have connected a cloud account

- fixbackend/workspaces/dependencies.py
- fixbackend/workspaces/models/__init__.py
- fixbackend/workspaces/router.py
- fixbackend/workspaces/schemas.py
> restrict user workspace access on trial end

- fixbackend/inventory/inventory_service.py
> [fix] Define result format

- fixbackend/notification/email/email_sender.py
> [feat] Improve from address

- fixbackend/config.py
- tests/fixbackend/workspaces/invitation_service_test.py
> [fix] Limits in trial

- fixbackend/app.py
- fixbackend/cloud_accounts/schemas.py
- fixbackend/config.py
- fixbackend/notification/discord/discord_notification.py
- fixbackend/notification/email/email_messages.py
- fixbackend/notification/email/templates/invite.html
- fixbackend/notification/email/templates/password_reset.html
- fixbackend/notification/email/templates/security_scan_finished.html
- fixbackend/notification/email/templates/signup.html
- fixbackend/notification/email/templates/verify_email.html
- fixbackend/notification/opsgenie/opsgenie_notification.py
- fixbackend/notification/pagerduty/pagerduty_notification.py
- fixbackend/notification/slack/slack_notification.py
- fixbackend/notification/teams/teams_notification.py
- tests/fixbackend/workspaces/invitation_service_test.py
Updates the string "FIX" to "Fix".
Should be pretty low risk except for maybe the changes in `fixbackend/cloud_accounts/schemas.py`.
Idk if I need to re-generate anything when changing the description there.
> Update FIX -> Fix

- fixbackend/analytics/analytics_event_sender.py
> [fix] Analytics sender need to be started

- fixbackend/analytics/analytics_event_sender.py
> [fix] posthog: use user_id as distinct id

- fixbackend/auth/user_manager.py
> [chore] improve logging

- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> Do not publish an event if zero accounts were collected

- fixbackend/config.py
- fixbackend/workspaces/models/__init__.py
- fixbackend/workspaces/trial_end_service.py
- tests/fixbackend/workspaces/router_test.py
> Make trial indefinite

- fixbackend/cloud_accounts/service_impl.py
> [fix] Do not report workspace collected event

- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> Handle failed jobs in dispatcher

- fixbackend/subscription/stripe_subscription.py
- tests/fixbackend/conftest.py
- tests/fixbackend/subscription/stripe_subscription_test.py
- tests/fixbackend/workspaces/router_test.py
> [feat] Allow company name and tax settings

- tests/fixbackend/workspaces/repository_test.py
- tests/fixbackend/workspaces/router_test.py
> Make test_expired_trials not flaky

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/domain_events/events.py
- fixbackend/subscription/aws_marketplace.py
- fixbackend/subscription/router.py
- fixbackend/subscription/stripe_subscription.py
- fixbackend/subscription/subscription_repository.py
- tests/fixbackend/cloud_accounts/service_test.py
> [feat] Handle stripe subscription cancelled messages

- fixbackend/__main__.py
- fixbackend/app.py
- fixbackend/app_dependencies.py
- fixbackend/dependencies.py
- tests/fixbackend/app_test.py
- tests/fixbackend/auth/users_router_test.py
- tests/fixbackend/billing/billing_info_router_test.py
- tests/fixbackend/cloud_accounts/router_test.py
- tests/fixbackend/conftest.py
- tests/fixbackend/events/router_test.py
- tests/fixbackend/permissions/roles_router_test.py
- tests/fixbackend/subscription/subscription_router_test.py
> [chore] Refactor app dependencies

- fixbackend/dependencies.py
> [fix] Handle missing dependencies

- fixbackend/workspaces/router.py
- fixbackend/workspaces/schemas.py
- tests/fixbackend/workspaces/router_test.py
> Add an endpoint for available invitation roles

- fixbackend/workspaces/router.py
- fixbackend/workspaces/schemas.py
- tests/fixbackend/workspaces/invitation_service_test.py
> Use workspace member as a default role when inviting

- fixbackend/permissions/router.py
- tests/fixbackend/permissions/roles_router_test.py
> Do not let users update their own roles

- fixbackend/app_dependencies.py
- fixbackend/auth/user_repository.py
- fixbackend/customer_support/router.py
- fixbackend/customer_support/templates/base.html
- fixbackend/customer_support/templates/roles/modal.html
- fixbackend/customer_support/templates/user_workspaces/add_success.html
- fixbackend/customer_support/templates/user_workspaces/index.html
- fixbackend/customer_support/templates/user_workspaces/select.html
- fixbackend/customer_support/templates/user_workspaces/table.html
- fixbackend/customer_support/templates/user_workspaces/workspace_modal.html
- fixbackend/customer_support/templates/workspaces/index.html
- static/css/style.css
> support adding users to the workspace

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
> [fix] Update account name with force

- fixbackend/domain_events/subscriber.py
- fixbackend/workspaces/schemas.py
> Hide workspace members in the API and add better event logging.

- fixbackend/app_dependencies.py
- fixbackend/inventory/inventory_service.py
- poetry.lock
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_service_test.py
- tests/fixbackend/notification/scheduled_email_test.py
> [feat] Introduce worker queue and reapply the name change again

- fixbackend/billing/schemas.py
- fixbackend/billing/service.py
> Correctly show stripe in the list of payment methods

- fixbackend/notification/notification_router.py
> [fix] Add slack

- fixbackend/notification/email/email_sender.py
- fixbackend/notification/email/scheduled_email.py
- fixbackend/notification/email/status_update_email_creator.py
- fixbackend/notification/email/templates/status-update.html
- tests/fixbackend/conftest.py
> [fix] Send images in Email inline

- fixbackend/app.py
> Add middleware to silence error when client disconnects early

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/dispatcher/collect_progress.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/domain_events/events.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> Add TenantAccountsCollectFailed event and use it when updating last collected rows in cloud accounts table

- fixbackend/notification/email/email_sender.py
> Update noreply -> support

- fixbackend/app_dependencies.py
- static/css/style.css
> Update support dependencies

- fixbackend/inventory/inventory_service.py
> [fix] Count all changes of vulnerable and compliant

- fixbackend/notification/email/scheduled_email.py
> [fix] Ignore workspaces that haven't been collected

- fixbackend/workspaces/dependencies.py
> Allow fetching workspace when logged in as an owner.

- fixbackend/cloud_accounts/service_impl.py
> feat: Include context kind in domain event log message

- fixbackend/notification/email/scheduled_email.py
> [fix] Better logging for scheduled emails

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/domain_events/events.py
- fixbackend/notification/email/email_messages.py
- fixbackend/notification/email/templates/account_degraded.html
- fixbackend/notification/email/templates/account_deleted.html
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/domain_events/test_events.py
- tests/fixbackend/notification/notification_service_test.py
> Send different message in case of the deleted CF stack

- fixbackend/app_dependencies.py
- fixbackend/auth/user_verifier.py
- fixbackend/customer_support/router.py
- fixbackend/customer_support/templates/user_workspaces/index.html
> Add send verification email button

- fixbackend/notification/email/status_update_email_creator.py
> [fix] Instances Total

- fixbackend/auth/user_verifier.py
- fixbackend/customer_support/router.py
> support: fix email verification workflow

- fixbackend/customer_support/roles_router.py
- fixbackend/customer_support/router.py
- fixbackend/customer_support/user_workspaces_router.py
> support: split router into multiple files

- fixbackend/app.py
> [fix] dev router with nonce

- fixbackend/analytics/analytics_event_sender.py
- fixbackend/analytics/domain_event_to_analytics.py
- fixbackend/analytics/events.py
- fixbackend/analytics/router.py
- fixbackend/cloud_accounts/service_impl.py
- fixbackend/domain_events/events.py
- tests/fixbackend/analytics/analytics_event_sender_test.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
- tests/fixbackend/domain_events/test_events.py
- tests/fixbackend/workspaces/invitation_service_test.py
> [feat] Events with id and timestamp

- fixbackend/notification/email/scheduled_email.py
- fixbackend/notification/email/status_update_email_creator.py
- tests/fixbackend/notification/scheduled_email_test.py
> [feat] Make sure the status update has a counting pixel

- fixbackend/workspaces/router.py
- fixbackend/workspaces/schemas.py
- tests/fixbackend/workspaces/router_test.py
> fix: Update workspace router to include user roles in response

- fixbackend/notification/email/scheduled_email.py
> [fix] Use different kinds for weekly and monthly

- fixbackend/collect/collect_queue.py
- tests/fixbackend/collect/collect_queue_test.py
> [feat] Define GcpProject and AzureSubscription

- fixbackend/permissions/models.py
- fixbackend/workspaces/router.py
- fixbackend/workspaces/schemas.py
- tests/fixbackend/workspaces/router_test.py
> Update workspace router to include user permissions in response

- fixbackend/app_dependencies.py
- fixbackend/cloud_accounts/service_impl.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/dispatcher/next_run_repository.py
- fixbackend/subscription/stripe_subscription.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/conftest.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
- tests/fixbackend/dispatcher/next_run_repository_test.py
> [fix] Adjust next run when product tier changes

- fixbackend/customer_support/user_workspaces_router.py
- fixbackend/subscription/router.py
- noxfile.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> [chore] Remove print statements

- fixbackend/billing/service.py
> Store payment method when recording billing usage metrics

- fixbackend/auth/router.py
- poetry.lock
- pyproject.toml
> [feat] Reject disposable email addresses

- fixbackend/dispatcher/collect_progress.py
- fixbackend/dispatcher/dispatcher_service.py
> Fix the missing task_id bug by making this field optional

- fixbackend/domain_events/subscriber.py
- tests/fixbackend/domain_events/subscriber_test.py
> [feat] Apply the backoff for each handler separately

- fixbackend/workspaces/router.py
> [feat] Do not allow disposable emails in invite

- fixbackend/notification/email/email_messages.py
- fixbackend/notification/email/status_update_email_creator.py
- fixbackend/notification/email/templates/status-update.html
- fixbackend/notification/email/templates/status-update.txt
- tests/fixbackend/notification/email_messages_test.py
> [feat] Add buckets to the status update

- fixbackend/app_dependencies.py
- fixbackend/notification/email/scheduled_email.py
- tests/fixbackend/notification/scheduled_email_test.py
> [feat] Send emails on sunday

- fixbackend/billing/router.py
- fixbackend/subscription/subscription_repository.py
> [fix] Sort billing entries desc

- fixbackend/customer_support/templates/users/user.html
> Align the button

- fixbackend/auth/user_repository.py
- fixbackend/customer_support/templates/users/index.html
- fixbackend/customer_support/users_router.py
- static/css/style.css
> Support: add pagination to the user list

- fixbackend/app.py
- fixbackend/billing/router.py
- fixbackend/config.py
- fixbackend/inventory/router.py
> [feat] Provide product tier settings via API

- tests/fixbackend/conftest.py
> [feat] Allow turning off DB migrations for local tests

- fixbackend/customer_support/templates/users/index.html
- fixbackend/customer_support/templates/users/user.html
- fixbackend/customer_support/users_router.py
> Customer support: allow user restore and disable caching on user page

- fixbackend/notification/email/email_messages.py
- tests/fixbackend/notification/email_messages_test.py
> [fix] Unit name

- fixbackend/cloud_accounts/gcp_service_account_service.py
> Fix the gcp service account info

- fixbackend/app_dependencies.py
- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/conftest.py
> Add GCP service account repository for managing service account keys

- fixbackend/customer_support/templates/users/index.html
- fixbackend/customer_support/templates/users/index_pagination.html
- fixbackend/customer_support/users_router.py
> Customer support: fix pagination

- fixbackend/dispatcher/dispatcher_service.py
> Support GCP in tracking collection progress

- fixbackend/customer_support/templates/users/index.html
> support: speedup user page load

- fixbackend/app.py
Fix replace google analytics with ph.fix.security in csp headers
> Fix replace google analytics with ph.fix.security in csp headers

- fixbackend/analytics/domain_event_to_analytics.py
- fixbackend/cloud_accounts/service_impl.py
- fixbackend/domain_events/events.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/domain_events/sender_impl_test.py
- tests/fixbackend/domain_events/test_events.py
> Rename AWS cloud account events

- fixbackend/notification/email/status_update_email_creator.py
- fixbackend/notification/email/templates/base.html
- fixbackend/notification/email/templates/status-update.html
- fixbackend/notification/email/templates/status-update.txt
- tools/contexts/status-update.yaml
- tools/render_template.py
> Add deep links and remove buckets

- fixbackend/cloud_accounts/models/__init__.py
- fixbackend/cloud_accounts/models/orm.py
- fixbackend/cloud_accounts/repository.py
- fixbackend/cloud_accounts/router.py
- fixbackend/cloud_accounts/schemas.py
- fixbackend/cloud_accounts/service_impl.py
- fixbackend/inventory/inventory_service.py
- migrations/versions/2024-05-24T10:57:25Z_store_last_task_id_on_cloud_account.py
- tests/fixbackend/cloud_accounts/repository_test.py
- tests/fixbackend/cloud_accounts/router_test.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/conftest.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
- tests/fixbackend/inventory/inventory_service_test.py
> Add an endpoint to query logs from failed to collect cloud accounts

- fixbackend/cloud_accounts/gcp_service_account_repo.py
- fixbackend/cloud_accounts/gcp_service_account_service.py
- fixbackend/cloud_accounts/models/__init__.py
- fixbackend/cloud_accounts/router.py
- fixbackend/cloud_accounts/schemas.py
- migrations/versions/2024-05-29T13:33:58Z_add_an_error_field_to_gcp_service_.py
- tests/fixbackend/conftest.py
> Show gcp account setup errors

- fixbackend/cloud_accounts/router.py
> Return 422 on problems with gcp service account key access

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/notification/email/email_messages.py
- fixbackend/notification/email/templates/account_degraded.html
- tests/fixbackend/notification/notification_service_test.py
> Include the cloud name in the degraded account notification

- fixbackend/workspaces/router.py
> Send workspace id as a fragment when inviting to workspace

- fixbackend/app_dependencies.py
- fixbackend/auth/api_token_service.py
- tests/fixbackend/conftest.py
> Fix token api errors

- fixbackend/notification/email/templates/signup.html
Updates the welcome Email template to have more practical links in it. I found it odd that the first thing we'd recommend to new signups is not related to the product they sign up for but instead tell them to read our blog and check out our linkedin.
> Update Email template

- fixbackend/cloud_accounts/azure_subscription_service.py
> better azure import logging

- fixbackend/cloud_accounts/azure_subscription_service.py
> hide warnings in azure client

- fixbackend/cloud_accounts/repository.py
- tests/fixbackend/cloud_accounts/repository_test.py
> Fix cloud account azure repo

- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/schemas.py
> [feat] Sort accounts by size

- fixbackend/subscription/router.py
> Add a default value to the product tier in the AWS callback

- fixbackend/subscription/router.py
- tests/fixbackend/subscription/subscription_router_test.py
> Redirect back after subscription using the absolute url

- fixbackend/cloud_accounts/azure_subscription_repo.py
- fixbackend/cloud_accounts/models/__init__.py
- fixbackend/cloud_accounts/router.py
- fixbackend/cloud_accounts/schemas.py
- migrations/versions/2024-06-17T15:00:22Z_your_message.py
- tests/fixbackend/cloud_accounts/azure_subscription_repo_test.py
> Remove subscription id

- fixbackend/notification/email/email_messages.py
- tests/fixbackend/notification/email_messages_test.py
> [fix] Show 0-3 as such

- fixbackend/notification/email/templates/trial_expired.html
- fixbackend/notification/email/templates/trial_expires.html
> Remove the extra login button in trial emails

- fixbackend/workspaces/invitation_service.py
> Log payment on hold error separately when inviting users

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/subscription/aws_marketplace.py
- tests/fixbackend/cloud_accounts/service_test.py
> Handle subscription created event to cleanup payment onhold

- fixbackend/workspaces/invitation_service.py
> Use better messages for errors

- fixbackend/workspaces/trial_end_service.py
> Run trial end service immediately after app start

- fixbackend/app_dependencies.py
- fixbackend/dependencies.py
> Enable trial end service

- fixbackend/workspaces/repository.py
> Allow downgrading to free with missing subscription

- fixbackend/config.py
- fixbackend/workspaces/trial_end_service.py
Reverts someengineering/fixbackend#526
> Revert "Remove endless trial"

- fixbackend/notification/email/one_time_email.py
> Do not use taskgroup to not exhaust the sqlalchemy pool

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/workspaces/trial_end_service.py
> Fix exception handling in trial end service

- fixbackend/workspaces/trial_end_service.py
> Do dry run on moving accounts to free tier

- fixbackend/cloud_accounts/service_impl.py
> Disable only the valid accounts

- fixbackend/config.py
- fixbackend/workspaces/trial_end_service.py
> Move accounts from trial to free

- fixbackend/workspaces/models/__init__.py
- fixbackend/workspaces/models/orm.py
- fixbackend/workspaces/repository.py
- fixbackend/workspaces/router.py
- fixbackend/workspaces/schemas.py
- migrations/versions/2024-06-27T14:05:21Z_store_free_tier_ack.py
- tests/fixbackend/workspaces/repository_test.py
- tests/fixbackend/workspaces/router_test.py
> Add ack move to free flag to the workspace

- fixbackend/workspaces/repository.py
> Change get_product_tier method to make it the same as workspace

- tests/fixbackend/notification/scheduled_email_test.py
> [fix] Fix test

- fixbackend/customer_support/templates/workspaces/workspace.html
- fixbackend/customer_support/workspaces_router.py
- fixbackend/graph_db/service.py
> Support: fix the missing graphdb access

- fixbackend/customer_support/workspaces_router.py
> Fix an issue in create_graph_db_access method in support

- fixbackend/cloud_accounts/gcp_service_account_service.py
> [fix] Ignore  gcp sys projects

- fixbackend/streaming_response.py
> [fix] Empty streams

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_router.py
- fixbackend/inventory/inventory_schemas.py
> feat: Add history timeline

- fixbackend/inventory/inventory_router.py
- fixbackend/inventory/inventory_service.py
- tests/fixbackend/inventory/inventory_service_test.py
> feat: Show longer timeline for free accounts

- fixbackend/collect/collect_queue.py
- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/collect/collect_queue_test.py
> Azure graph collection

- fixbackend/app.py
allow data in connect-src in csp headers
> [fix]: allow data in connect-src in csp headers

- fixbackend/app.py
Allow cdn in connect-src in csp headers
> [fix] Allow cdn in connect-src in csp headers

- fixbackend/collect/collect_queue.py
- fixbackend/dispatcher/collect_progress.py
- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> Add a post collect step

- fixbackend/collect/collect_queue.py
- fixbackend/dispatcher/collect_progress.py
- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
Reverts someengineering/fixbackend#567
> Revert "Add a post collect step"

- fixbackend/app.py
> [fix] allow ph.fix.security in csp

- fixbackend/collect/collect_queue.py
- fixbackend/dispatcher/collect_progress.py
- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
> Post collect job support

- fixbackend/app.py
- fixbackend/auth/router.py
> Log security events

- fixbackend/customer_support/login_router.py
> Use https in redirect_uri when not on localhost

- fixbackend/cloud_accounts/service_impl.py
> Update next tenant run on new subscription

- fixbackend/app_dependencies.py
> Use repeatable read isolaton level

- fixbackend/cloud_accounts/service_impl.py
- fixbackend/config.py
- tests/fixbackend/conftest.py
> fix: only degrade when no resource is collected

- fixbackend/cloud_accounts/models/__init__.py
- fixbackend/cloud_accounts/models/orm.py
- fixbackend/cloud_accounts/repository.py
- fixbackend/cloud_accounts/schemas.py
- fixbackend/cloud_accounts/service.py
- fixbackend/dispatcher/collect_progress.py
- fixbackend/dispatcher/dispatcher_service.py
- fixbackend/domain_events/events.py
- migrations/versions/2024-08-07T11:04:18Z_add_resource_error_count_to_cloud_.py
- tests/fixbackend/billing/billing_info_service_test.py
- tests/fixbackend/cloud_accounts/repository_test.py
- tests/fixbackend/cloud_accounts/router_test.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
- tests/fixbackend/domain_events/test_events.py
- tests/fixbackend/notification/notification_service_test.py
> Store resource collection errors inside the cloud account

- fixbackend/app_dependencies.py
- fixbackend/cloud_accounts/models/__init__.py
- fixbackend/cloud_accounts/models/orm.py
- fixbackend/cloud_accounts/repository.py
- fixbackend/cloud_accounts/service.py
- fixbackend/config.py
- fixbackend/dispatcher/dispatcher_service.py
- tests/fixbackend/cloud_accounts/repository_test.py
- tests/fixbackend/cloud_accounts/router_test.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/conftest.py
> Periodically ping degraded accounts

- fixbackend/app.py
> Handle user not exists exception as 404

- fixbackend/inventory/inventory_service.py
> Filter out accounts without a score when asking for report summary

- fixbackend/config.py
- fixbackend/customer_support/login_router.py
- tests/fixbackend/conftest.py
> Explicitly set a base url for support

- fixbackend/cloud_accounts/service.py
- tests/fixbackend/inventory/inventory_service_test.py
> Do no issue the degraded event again if the account is already in a degraded state

- fixbackend/cloud_accounts/service.py
- tests/fixbackend/cloud_accounts/router_test.py
> Enable accounts as soon as  subscription is available

- fixbackend/app.py
> Replace message with detail in error JSON

- fixbackend/collect/collect_queue.py
- fixbackend/dispatcher/dispatcher_service.py
> Log more in trigger_collect

- fixbackend/inventory/inventory_service.py
- fixbackend/notification/email/status_update_email_creator.py
> [fix] Count only resources with an account

- fixbackend/cloud_accounts/schemas.py
- tests/fixbackend/cloud_accounts/router_test.py
> Fix cloud account enabled bug

- .devcontainer/devcontainer.json
- fixbackend/auth/user_manager.py
- package-lock.json
- package.json
- tests/fixbackend/auth/router_test.py
> Add the minimum password length requirements

- fixbackend/cloud_accounts/service.py
> allow enabling degraded accounts

- fixbackend/config.py
Reduce session time from one week to 48h
> Reduce session time from one week to 48h

- fixbackend/inventory/inventory_service.py
> fix rounding in inventory service

- fixbackend/cloud_accounts/schemas.py
> Add a tenant id and a client id to the azure credentials endpoint

- fixbackend/inventory/inventory_router.py
- fixbackend/inventory/inventory_schemas.py
> [feat] Add aggregation endpoint

- fixbackend/auth/schemas.py
- fixbackend/auth/user_manager.py
- tests/fixbackend/auth/router_test.py
> Require current password when updating password

- fixbackend/__main__.py
> Fix https url generation in support

- fixbackend/inventory/inventory_router.py
- fixbackend/inventory/inventory_schemas.py
- fixbackend/inventory/inventory_service.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Allow defining the properties to show

- fixbackend/inventory/inventory_router.py
- fixbackend/inventory/inventory_service.py
> [feat] Endpoint to request descendant summaries

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_router.py
> [feat] Allow definition of keys in metadata section

- fixbackend/inventory/inventory_router.py
- fixbackend/inventory/inventory_schemas.py
- fixbackend/inventory/inventory_service.py
> [feat] Allow filtering descendant summary

- fixbackend/inventory/inventory_service.py
> [fix] Descendant Summary Account Usage

- fixbackend/cloud_accounts/azure_subscription_repo.py
> Use updated timestamp when pinging new subscriptions

- fixbackend/cloud_accounts/azure_subscription_repo.py
> Fix created_at on upsert

- fixbackend/cloud_accounts/azure_subscription_repo.py
- fixbackend/cloud_accounts/azure_subscription_service.py
> Do not ping azure subscriptions which are good to go

- fixbackend/inventory/inventory_service.py
- tests/fixbackend/inventory/inventory_service_test.py
> [fix] Top 5 failing
