- fixbackend/app.py
- fixbackend/config.py
- tests/fixbackend/conftest.py
Starting `fixbackend --dispatcher` will start the backend in dispatching mode.
The API that is provided has /ready /healthy and /metrics but not the /api endpoints.
It allows starting different background tasks than in API mode.
> [feat] Enable the dispatcher mode

- fixbackend/subscription/router.py
> [fix] marketplace return url

- fixbackend/app.py
- fixbackend/cloud_accounts/models/__init__.py
- fixbackend/cloud_accounts/service_impl.py
- fixbackend/config.py
- fixbackend/subscription/aws_marketplace.py
- tests/fixbackend/cloud_accounts/service_test.py
- tests/fixbackend/conftest.py
- tests/fixbackend/inventory/inventory_client_test.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Handle CloudFormation notifications

- fixbackend/permissions/router.py
- fixbackend/workspaces/router.py
- fixbackend/workspaces/schemas.py
- tests/fixbackend/workspaces/router_test.py
> Return a better workspace user roles json

- fixbackend/auth/user_manager.py
> Do not block the thread during hashing

- fixbackend/inventory/router.py
- fixbackend/inventory/schemas.py
> [feat] Allow ignoring resources from security checks

- fixbackend/inventory/inventory_client.py
- fixbackend/inventory/inventory_service.py
- fixbackend/inventory/router.py
- fixbackend/notification/notification_service.py
- fixbackend/streaming_response.py
- tests/fixbackend/inventory/inventory_client_test.py
- tests/fixbackend/inventory/inventory_service_test.py
- tests/fixbackend/streaming_response_test.py
> [feat] stream content where possible

- fixbackend/cloud_accounts/service_impl.py
> Add more event logging and timeout for cloud account event handler

- fixbackend/app.py
- pyproject.toml
> Include redis and mysql in the healthcheck

- fixbackend/analytics/analytics_event_sender.py
- fixbackend/analytics/domain_event_to_analytics.py
- fixbackend/analytics/events.py
- fixbackend/config.py
- fixbackend/domain_events/events.py
- fixbackend/workspaces/repository.py
- poetry.lock
- pyproject.toml
- tests/fixbackend/conftest.py
- tests/fixbackend/dispatcher/dispatcher_service_test.py
- tests/fixbackend/domain_events/test_events.py
- tests/fixbackend/inventory/inventory_service_test.py
> [feat] Use posthog analytics sender

- fixbackend/auth/user_manager.py
- tests/fixbackend/auth/router_test.py
- tests/fixbackend/conftest.py
> Reduce test flakiness

- fixbackend/inventory/inventory_service.py
> Make sure benchmark info is a dict

- fixbackend/cloud_accounts/service.py
Something is wrong with Email sending for GCP account degradation. In the past 6h I received 42 Emails for the same account and the system won't shut up about it.
This temporarily patches out the GCP email sending for degraded accounts until we have a proper fix.
> Silence GCP degradation

- fixbackend/cloud_accounts/repository.py
- tests/fixbackend/cloud_accounts/repository_test.py
> Fix the cloud account repository update method

- fixbackend/cloud_accounts/service.py
> Move accounts back to configured if failed scan count is zero

- fixbackend/auth/rate_limiter.py
- fixbackend/auth/router.py
- fixbackend/config.py
- tests/fixbackend/auth/rate_limiter_test.py
- tests/fixbackend/conftest.py
> Rate limiting: decrement on auth check

- fixbackend/auth/user_manager.py
- tests/fixbackend/auth/router_test.py
> Calculate pw hash consistently with auth logic

- fixbackend/inventory/inventory_router.py
- fixbackend/inventory/inventory_schemas.py
- fixbackend/inventory/inventory_service.py
> [feat] Endpoint to request timeseries

- fixbackend/inventory/inventory_router.py
- fixbackend/inventory/inventory_schemas.py
- fixbackend/inventory/inventory_service.py
> [feat] Provide one summary for all kinds

- fixbackend/auth/schemas.py
- fixbackend/notification/user_notification_repo.py
- migrations/versions/2024-10-01T14:23:11Z_email_marketing.py
- tests/fixbackend/auth/users_router_test.py
- tests/fixbackend/notification/user_notification_repo_test.py
> [feat] user notification settings: add marketing column

- fixbackend/app.py
- fixbackend/auth/auth_backend.py
- fixbackend/auth/depedencies.py
- fixbackend/auth/models/orm.py
- fixbackend/auth/transport.py
- fixbackend/auth/user_manager.py
- fixbackend/auth/user_repository.py
- fixbackend/auth/users_router.py
- migrations/versions/2024-10-07T09:24:49Z_user_last_login_and_activity.py
- tests/fixbackend/auth/router_test.py
> [feat] Maintain last_login and last_active timestamps per user

- fixbackend/cloud_accounts/azure_subscription_repo.py
- fixbackend/cloud_accounts/service.py
- tests/fixbackend/cloud_accounts/azure_subscription_repo_test.py
> Set can_access_account flag to false when updating creds
